server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tu-usuario/config-repo
          clone-on-start: true
  application:
    name: config-server